---
- name: STOP and disable Github Actions Runner service
  win_service:
    name: "actions.runner.service"
    state: stopped

# - name: Uninstall runner
#   win_command: ".\\config.cmd remove --unattended --auth pat --token {{ registration.json.token }}"
#   args:
#     chdir: "{{ runner_dir_win }}"
#   when: reinstall_runner or runner_state|lower == "absent"

- name: Check GitHub Actions runner file
  ansible.windows.win_stat:
    path: "{{ runner_dir_win }}\\.runner"
  register: runner_file

- name: Unregister runner from the GitHub
  environment:
    RUNNER_ALLOW_RUNASROOT: "1"
  ansible.windows.win_command: ".\\config.cmd remove --token {{ registration.json.token }} --name {{ runner_name }} --unattended"
  args:
    chdir: "{{ runner_dir_win }}"
  # become: false
  # become_user: "{{ runner_user }}"
  no_log: false #"{{ hide_sensitive_logs | bool }}"
  when: runner_name in registered_runners.json.runners|map(attribute='name')|list and runner_file.stat.exists

- name: Delete runner directory
  ansible.windows.win_file:
    path: "{{ runner_dir_win }}"
    state: absent
